# https://codecombat.com/play/level/banefire?
# The ogre looks big and slow. Movement will help you avoid his deadly attacks.
hero.moveRight()
hero.moveUp()
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")