# https://codecombat.com/play/level/twisted-canyon?
# Escape from the maze by moving to the X mark.
# Try to collect as many coins as you can.
hero.attack("Treasure Chest")
hero.moveRight()
hero.moveLeft(2)
hero.moveDown()
hero.moveRight(3)
hero.attack("Door")
hero.moveRight(2)
hero.moveLeft(2)
hero.moveUp(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()
hero.moveUp(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()
hero.moveUp(2)
enemy = hero.findNearestEnemy()
hero.attack(enemy)
hero.moveLeft(2)
hero.moveRight(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()